#!/usr/bin/env python3
GeneralFormatOpList = []
SignOpList = []
UnsignOpList = []
SpWsignOpList = []
SpWUnsignOpList = []
SpVOplist = []
SpMaskOpList = []
Sp2MaskOpList = []
WSignOpList = []
WUnsignOpList = []
SpecialFormatList = []
SpVOplist = []
Sp2VOplist = []
ZeroExtOpList = []
SignExtOpList = []
