#!/usr/bin/env python3
GeneralFormatOpList = []
SignOpList = ['vsadd', 'vasub', 'vssub', 'vaadd', 'vssra', 'vsmul']
UnsignOpList = ['vssubu', 'vsaddu', 'vssrl', 'vasubu', 'vaaddu']
SpWsignOpList = []
SpWUnsignOpList = []
SpVOplist = []
SpMaskOpList = []
Sp2MaskOpList = []
WSignOpList = []
WUnsignOpList = []
SpecialFormatList = []
SpVOplist = []
Sp2VOplist = []
ZeroExtOpList = []
SignExtOpList = []
RMOpList = []
