#!/usr/bin/env python3
GeneralFormatOpList = []
SignOpList = ['vsadd', 'vssra', 'vssub', 'vaadd', 'vasub', 'vsmul']
UnsignOpList = ['vssubu', 'vssrl', 'vasubu', 'vsaddu', 'vaaddu']
SpWsignOpList = []
SpWUnsignOpList = []
SpVOplist = []
SpMaskOpList = []
Sp2MaskOpList = []
WSignOpList = []
WUnsignOpList = []
SpecialFormatList = []
SpVOplist = []
Sp2VOplist = []
ZeroExtOpList = []
SignExtOpList = []
RMOpList = ['vssra', 'vssrl', 'vasubu', 'vnclip', 'vaadd', 'vasub', 'vsmul', 'vnclipu', 'vaaddu']
