#!/usr/bin/env python3
GeneralFormatOpList = ['vmacc', 'vnmsac', 'vmadd', 'vand', 'vadd', 'vsll', 'vsub', 'vor', 'vmsne', 'vmul', 'vmseq', 'vxor', 'vnmsub']
SignOpList = ['vmin', 'vmulhsu', 'vmax', 'vmsge', 'vmsle', 'vmslt', 'vmsgt', 'vsra', 'vdiv', 'vmulh', 'vrem']
UnsignOpList = ['vmaxu', 'vremu', 'vmsgeu', 'vsrl', 'vmulhu', 'vmsltu', 'vminu', 'vdivu', 'vmsgtu', 'vmsleu']
SpWsignOpList = ['vwmaccsu', 'vwmacc', 'vwmulsu', 'vwmul']
SpWUnsignOpList = ['vwmaccu', 'vwmulu']
SpVOplist = []
SpMaskOpList = ['vsbc', 'vmerge', 'vadc']
Sp2MaskOpList = ['vmadc', 'vmsbc']
WSignOpList = []
WUnsignOpList = []
SpecialFormatList = []
SpVOplist = []
Sp2VOplist = []
ZeroExtOpList = ['vzext']
SignExtOpList = ['vsext']
